version: '3'
services:
  db:
    image: my-mariadb-image
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db1
    ports:
      - "3306:3306"
  app:
    image: my-java-app-image
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    image: my-react-app-image
    ports:
      - "80:80"
