version: '3'

services:
  db:
    build: database/.
    #image: daniel225660/dashboard-monitoring-system:database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: db

  be:
    build: backend/.
    #image: daniel225660/dashboard-monitoring-system:backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME}?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - mrtg_data:/var/www/html/mrtg
    container_name: be

  fe:
    build: frontend/.
    #image: daniel225660/dashboard-monitoring-system:frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - mrtg_data:/var/www/html/mrtg
    container_name: fe
      
volumes:
  db_data:
  mrtg_data:
  