version: '3'

services:
  db:
    #build: database/.
    image: daniel225660/dashboard-monitoring-system:database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYS QL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    container_name: db

  be:
    #build: backend/.
    image: daniel225660/dashboard-monitoring-system:backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME}?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    container_name: be

  fe:
    #build: frontend/.
    image: daniel225660/dashboard-monitoring-system:frontend
    restart: always
    ports:
      - "80:80"
    container_name: fe
      
volumes:
  db_data:
  